import './../../common/common.scss'
import './../../components/button/button'
import './../../components/header/header'
import './../../components/welcome/welcome'
import './../../components/product/product'
import './../../components/products/products'
import './../../components/footer/footer'
