import './../../common/common.scss'
import './../../components/button/button'
import './../../components/header/header'
import './../../components/welcome-mobile/welcome-mobile'
import './../../components/footer/footer'
import './../../components/product-mobile/product-mobile'
import './../../components/products-mobile/products-mobile'
